export default {
  SIGN_UP: 'SIGN_UP',
  GET_USER_INFO: 'GET_USER_INFO',
  LOGGED_IN: 'LOGGED_IN',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  FETCH_MESSAGE: 'FETCH_MESSAGE',
  POST_WATCHLIST: 'POST_WATCHLIST',
  DELETE_WATCHLIST: 'DELETE_WATCHLIST',
  UPDATE_AVATAR: 'UPDATE_AVATAR'
}
